name: pipe
description: Pipeline for everything.
version: 1.0.0
homepage: https://github.com/AndreErvilha/pipe.git

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  ansicolor: ^2.0.1
  args: ^2.3.0
  recase: ^4.0.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

executables:
  pipe: pipe